apiVersion: v1
kind: Service
metadata:
  name: lb-ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - port: 20
      name: ftps-20
      protocol: TCP
      targetPort: 20
    - port: 21
      name: ftps-21
      protocol: TCP
      targetPort: 21
    - port: 2020
      name: ftps-2020
      protocol: TCP
      targetPort: 2020
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_my:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 2020