apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
    - port: 3000
      name: grafana
      protocol: TCP
      targetPort: 3000
    - port: 5000
      name: pma
      protocol: TCP
      targetPort: 5000
    - port: 5050
      name: wp
      protocol: TCP
      targetPort: 5050
  selector:
    app: nginx