apiVersion: v1
kind: Service
metadata:
  name: lb-pma
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
    - port: 5000
      name: pma
      protocol: TCP
      targetPort: 5000
  selector:
    app: pma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma_my:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000