apiVersion: v1
kind: Service
metadata:
  name: lb-wp
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  ports:
    - port: 5050
      name: wp
      protocol: TCP
      targetPort: 5050
  selector:
   app: wp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wp_my:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050